# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_remote_procedure.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='grpc_remote_procedure.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1bgrpc_remote_procedure.proto\"\x1e\n\x06\x61\x64\x64Msg\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\x17\n\x08imageMsg\x12\x0b\n\x03img\x18\x01 \x01(\x0c\"\x1b\n\x0c\x61\x64\x64MsgReturn\x12\x0b\n\x03\x61ns\x18\x01 \x01(\x05\"/\n\x0eimageMsgReturn\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x32&\n\x03\x61\x64\x64\x12\x1f\n\x03\x61\x64\x64\x12\x07.addMsg\x1a\r.addMsgReturn\"\x00\x32.\n\x05image\x12%\n\x05image\x12\t.imageMsg\x1a\x0f.imageMsgReturn\"\x00\x62\x06proto3'
)




_ADDMSG = _descriptor.Descriptor(
  name='addMsg',
  full_name='addMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='addMsg.a', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='b', full_name='addMsg.b', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=61,
)


_IMAGEMSG = _descriptor.Descriptor(
  name='imageMsg',
  full_name='imageMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='img', full_name='imageMsg.img', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=86,
)


_ADDMSGRETURN = _descriptor.Descriptor(
  name='addMsgReturn',
  full_name='addMsgReturn',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ans', full_name='addMsgReturn.ans', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=115,
)


_IMAGEMSGRETURN = _descriptor.Descriptor(
  name='imageMsgReturn',
  full_name='imageMsgReturn',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='imageMsgReturn.width', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='height', full_name='imageMsgReturn.height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=164,
)

DESCRIPTOR.message_types_by_name['addMsg'] = _ADDMSG
DESCRIPTOR.message_types_by_name['imageMsg'] = _IMAGEMSG
DESCRIPTOR.message_types_by_name['addMsgReturn'] = _ADDMSGRETURN
DESCRIPTOR.message_types_by_name['imageMsgReturn'] = _IMAGEMSGRETURN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

addMsg = _reflection.GeneratedProtocolMessageType('addMsg', (_message.Message,), {
  'DESCRIPTOR' : _ADDMSG,
  '__module__' : 'grpc_remote_procedure_pb2'
  # @@protoc_insertion_point(class_scope:addMsg)
  })
_sym_db.RegisterMessage(addMsg)

imageMsg = _reflection.GeneratedProtocolMessageType('imageMsg', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEMSG,
  '__module__' : 'grpc_remote_procedure_pb2'
  # @@protoc_insertion_point(class_scope:imageMsg)
  })
_sym_db.RegisterMessage(imageMsg)

addMsgReturn = _reflection.GeneratedProtocolMessageType('addMsgReturn', (_message.Message,), {
  'DESCRIPTOR' : _ADDMSGRETURN,
  '__module__' : 'grpc_remote_procedure_pb2'
  # @@protoc_insertion_point(class_scope:addMsgReturn)
  })
_sym_db.RegisterMessage(addMsgReturn)

imageMsgReturn = _reflection.GeneratedProtocolMessageType('imageMsgReturn', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEMSGRETURN,
  '__module__' : 'grpc_remote_procedure_pb2'
  # @@protoc_insertion_point(class_scope:imageMsgReturn)
  })
_sym_db.RegisterMessage(imageMsgReturn)



_ADD = _descriptor.ServiceDescriptor(
  name='add',
  full_name='add',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=166,
  serialized_end=204,
  methods=[
  _descriptor.MethodDescriptor(
    name='add',
    full_name='add.add',
    index=0,
    containing_service=None,
    input_type=_ADDMSG,
    output_type=_ADDMSGRETURN,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ADD)

DESCRIPTOR.services_by_name['add'] = _ADD


_IMAGE = _descriptor.ServiceDescriptor(
  name='image',
  full_name='image',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=206,
  serialized_end=252,
  methods=[
  _descriptor.MethodDescriptor(
    name='image',
    full_name='image.image',
    index=0,
    containing_service=None,
    input_type=_IMAGEMSG,
    output_type=_IMAGEMSGRETURN,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_IMAGE)

DESCRIPTOR.services_by_name['image'] = _IMAGE

# @@protoc_insertion_point(module_scope)
