##
## You provide this
##

FROM dirkcgrunwald/facerec:latest

LABEL maintainer="dirk grunwald <grunwald@colorado.edu>"

RUN pip3 install pika redis jsonpickle requests flask Pillow

WORKDIR /srv

COPY worker-server.py /srv

## ENV FLASK_APP=rest-server.py

EXPOSE 5001

CMD ["python3", "worker-server.py"]